services:
  - type: web
    name: shivkumar-kirana
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m flask db upgrade"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        sync: false

  - type: pserv
    name: shivkumar-db
    env: postgres
    region: oregon
    plan: free
    postgresVersion: "15"
